### ISSUE TITLE
SpriteEffects (FlipHorizontally and FlipVertically)

### ISSUE THREAD

**Issue by geirsagberg** [ezequias2d/peridot#2]
Hey, thanks a bunch for the work you've done, I'm using Peridot.Veldrid to build my own game engine on top of Veldrid!

I really enjoy that your spritebatch is quite close in API to MonoGames spriteBatch, but I'm currently trying to draw sprites flipped, and missing the `SpriteEffects.FlipHorizontally` and `SpriteEffects.FlipVertically` options.

Any plans on implementing those? I tried to give it a go by inverting the scale, but it doesn't seem to work correctly...

**Comment by ezequias2d** [comment]
I have an idea that it is caused by face culling, as the scale is applied to the sprite geometry which should cause the face side to flip, later I will fix the problem and release a 0.2.3-alpha version with some option to select which culling face to use in the backend with veldrid.

To implement sprite flipping in the future I will put the option (SpriteEffects, SpriteOptions or something like that) to invert the UV map in the shader, it should be less buggy to use this way.

**Comment by ezequias2d** [comment]
The bug should be solved now and thanks for finding the problem, I'm looking forward to seeing the result of your engine.

If you find any other bugs or think of something to put in the API, I'll be happy to accept your contribution. I'll keep the problem open while I implement the `FlipHorizontally` and `FlipVertically`.

**Comment by geirsagberg** [comment]
Thanks, the fix worked like a charm!

**Comment by ezequias2d** [comment]
Version 0.3.0-alpha now has an implementation for SpriteOptions(FlipHorizontally and FlipVertically).
