### ISSUE TITLE
GetBuffer includes matrix size in instance count

### ISSUE THREAD

**Issue by jimbuck** [ezequias2d/peridot#7]
Hey there! I was reviewing your repository so I could learn Veldrid and Sprite Batching, very cool project! I did see one thing that might be a bug:

https://github.com/ezequias2d/peridot/blob/96d592713eb0b1ac33e4e8297a842441fc08f421/src/Peridot.Veldrid/VSpriteBatch.cs#L57

The call is adding the _size_ of the projection matrix (which is `64`) to the number of items. The number of items is then multiplied by the `BatchItem` size (which is `80`) to get the target size of the buffer. Was adding 64 to the item count intentional? What if you just add 1 so the buffer includes another 80 bytes, and the project matrix can still prefix the buffer?

```
[ projectionMatrix(64) | spacer(16) | instance0(80), instance1(80), ..., instanceN(80)]
```

https://github.com/ezequias2d/peridot/blob/96d592713eb0b1ac33e4e8297a842441fc08f421/src/Peridot.Veldrid/VSpriteBatch.cs#L72-L78

**Comment by ezequias2d** [comment]
Oh, I think the solution would be to change the function to receive the size instead of the count.

https://github.com/ezequias2d/peridot/blob/96d592713eb0b1ac33e4e8297a842441fc08f421/src/Peridot.Veldrid/Resources/shader.vert#L21-L25

Since the std430 layout is being used, the Item structure is aligned to the highest alignment of its fields, so the alignment is 16 bytes (vec4 align).

https://github.com/ezequias2d/peridot/blob/96d592713eb0b1ac33e4e8297a842441fc08f421/src/Peridot.Veldrid/Resources/shader.vert#L11-L19

```
[ projectionMatrix(64) | instance0(80), instance1(80), ..., instanceN(80) | spacer(64 * 80 - 64 = 5056)] <= now
[ projectionMatrix(64) | instance0(80), instance1(80), ..., instanceN(80) | spacer(16)] <= group.Count + 1
```
Therefore adding 1 instead of 64 (bytes) didn't remove all the memory leak (5056 bytes), but it will reduce it to 16 bytes.

Here you can see when the copy to the GPU buffer is performed, the copy is aligned  to 16 bytes:
https://github.com/ezequias2d/peridot/blob/96d592713eb0b1ac33e4e8297a842441fc08f421/src/Peridot.Veldrid/VSpriteBatch.cs#L59-L63

**Comment by jimbuck** [comment]
Very interesting! I'm just getting into graphics programming so I appreciate the insight.

To avoid the unused 16 bytes is it as simple as making the buffer size like this?

```
var size = matrixSize + ((count + 63) & (~63)) * structSize; // matrixSize = 64 in this case. 
```
